spring.application.name=sb_carrent_mvc

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url =jdbc:mysql://localhost:3306/carrentdb
spring.datasource.username=root
spring.datasource.password=root